import { describe, expect, it } from "vitest";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

/**
 * `docs/ENVIRONMENT.md` says where each key belongs, and a reference that has
 * drifted is worse than none: someone adding a provider reads it, does not find
 * their key, and puts it wherever seems reasonable. `.env` seems reasonable, and
 * anything in `.env` is compiled into the bundle and published.
 *
 * So the doc is checked against the code rather than trusted: every secret the
 * functions actually read has to appear in it, and no `VITE_` variable may be
 * described as a secret, because there is no such thing.
 */
const root = process.cwd();
const doc = readFileSync(join(root, "docs", "ENVIRONMENT.md"), "utf8");

function functionSources(): string[] {
  const dir = join(root, "supabase", "functions");
  return readdirSync(dir)
    .filter((name) => statSync(join(dir, name)).isDirectory())
    // mcp/index.ts is generated by mcpPlugin(); it is not hand-maintained.
    .filter((name) => name !== "mcp")
    .map((name) => join(dir, name, "index.ts"))
    .filter((path) => {
      try {
        return statSync(path).isFile();
      } catch {
        return false;
      }
    })
    .map((path) => readFileSync(path, "utf8"));
}

/** Names the platform injects into every function; nobody sets these. */
const PLATFORM = new Set([
  "SUPABASE_URL",
  "SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
]);

function secretsTheFunctionsRead(): Set<string> {
  const found = new Set<string>();
  for (const src of functionSources()) {
    // Direct reads, plus the `const SECRET = "..."` each provider reads through.
    for (const [, name] of src.matchAll(/Deno\.env\.get\(\s*["']([A-Z0-9_]+)["']/g)) found.add(name);
    for (const [, name] of src.matchAll(/const SECRET\s*=\s*["']([A-Z0-9_]+)["']/g)) found.add(name);
    for (const [, name] of src.matchAll(/allowlistFromEnv\(\s*["']([A-Z0-9_]+)["']/g)) found.add(name);
  }
  for (const name of PLATFORM) found.delete(name);
  return found;
}

describe("the environment reference", () => {
  it("finds the functions to check", () => {
    expect(functionSources().length).toBeGreaterThan(20);
  });

  it("names every secret the edge functions actually read", () => {
    const missing = [...secretsTheFunctionsRead()].filter((name) => !doc.includes(name)).sort();
    expect(missing).toEqual([]);
  });

  it("names every VITE_ variable the browser actually reads", () => {
    const src = readFileSync(join(root, "src", "lib", "edgeFunction.ts"), "utf8");
    const used = [...src.matchAll(/import\.meta\.env\.(VITE_[A-Z0-9_]+)/g)].map((m) => m[1]);
    expect(used.length).toBeGreaterThan(0);
    expect(used.filter((name) => !doc.includes(name))).toEqual([]);
  });

  it("never lists a VITE_ variable among the secrets", () => {
    // Vite inlines VITE_* into the bundle, so a "secret" one is a contradiction.
    const secretsSection = doc.slice(doc.indexOf("## Cloud → Secrets"));
    expect(secretsSection).not.toMatch(/VITE_[A-Z0-9_]+/);
  });

  it("keeps the publishable key out of the Authorization header, in writing too", () => {
    expect(doc).toMatch(/apikey/);
    expect(doc).toMatch(/never as a bearer token/i);
  });
});
