#!/bin/bash
# Backup Retention Policy Script for AI Workstation
# Generated by System Organizer AI
# Date: 2025-08-27

RETENTION_DAYS=30          # Keep backups for 30 days
BACKUP_DIR="E:/AI_Permanent/Models/backups"
SOURCE_DIR="C:/Users/Eru/AI_ Workspace/models/LM_Studio/Models"
LOG_FILE="C:/Users/Eru/AI_ Workspace/logs/backup_retention.log"

# Create backup directory if it does not exist
mkdir -p "$BACKUP_DIR"

echo "========================================"
echo "Backup Retention Policy Execution"
echo "Date: $(date)"
echo "Retention Period: $RETENTION_DAYS days"
echo "Backups stored in: $BACKUP_DIR"
echo "========================================"

# Step 1: Create timestamped backup of all models
BACKUP_TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
BACKUP_PATH="$BACKUP_DIR/backup_$BACKUP_TIMESTAMP"

echo "[1/4] Creating timestamped backup..."
mkdir -p "$BACKUP_PATH"
cp -r "$SOURCE_DIR" "$BACKUP_PATH/" 2>&1 | tee -a "$LOG_FILE"

# Step 2: Compress the backup
if [ -d "$BACKUP_PATH" ]; then
    tar -czf "$BACKUP_PATH.tar.gz" -C "$(dirname $BACKUP_PATH)" "$(basename $BACKUP_PATH)
        echo "Backup compressed to: $BACKUP_PATH.tar.gz"
else
    echo "ERROR: Backup directory not created!"
fi

# Step 2: Remove old backups (older than RETENTION_DAYS)
echo "[2/4] Removing old backups older than $RETENTION_DAYS days..."
find "$BACKUP_DIR" -name "*.tar.gz" -mtime +"$RETENTION_DAYS" -delete 2>&1 | tee -a "$LOG_FILE"

# Step 3: Verify backup integrity (spot check)
echo "[3/4] Verifying backup integrity..."
if [ -f "$BACKUP_PATH.tar.gz" ]; then
    tar -tzf "$BACKUP_PATH.tar.gz" > /dev/null && echo "Backup integrity verified!"
else
fi

# Step 4: Generate cleanup report
echo "[4/4] Generating cleanup report..."
current_backups=$(ls "$BACKUP_DIR"/*.tar.gz | wc -l)
total_size=$(( $(du -sh "$BACKUP_DIR"' | cut -f1 | tr -d " ") * 1024 ))

echo "Backups retained: $current_backups"
echo "Total storage used: ${total_size} KB"

# Log the entire session
echo "========================================" >> "$LOG_FILE"
echo "Backup retention complete. Backups retained: $current_backups" >> "$LOG_FILE"
echo "Total storage used: ${total_size} KB" >> "$LOG_FILE"
echo "Date: $(date)" >> "$LOG_FILE"
echo "========================================" >> "$LOG_FILE"
