#!/usr/bin/env python3
"""
Hybrid Router Script for AI Workstation
- Routes models to CPU/GPU/DRAM based on capability requirements
- Supports multiple model families (QWYTHOS, Muse Glimmer, GPT OSS)
- Includes automatic fallback and load balancing

Generated by System Organizer AI
Date: 2025-08-27
"""

import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional


class ModelConfig:
    """Configuration for a single AI model."""
    
    def __init__(self, name: str, paths: List[str], 
                 gpu_memory_mb: float, cpu_cores: int, 
                 recommended_gpu: str = "any", 
                 supported_formats: List[str] = None):
        self.name = name
        self.paths = paths  # [FP16 GGUF, Q4_K_M GGUF]
        self.gpu_memory_mb = gpu_memory_mb
        self.cpu_cores = cpu_cores
        self.recommended_gpu = recommended_gpu
        self.supported_formats = supported_formats or ["f16", "q4km"]
        
    def get_best_path(self) -> Optional[str]:
        """Return the best path based on current system resources."""
        for fmt in self.supported_formats:
            # Check if path exists (format-specific naming)
            for p in self.paths:
                if f"{fmt}.gguf" in p.lower():
                    return p
        return None


class HybridRouter:
    """
    Routes AI inference requests to the optimal compute resource.
    
    Architecture:
    - GPU: Main brain (Qwen2 7B/14B/32B, SDXL, Flux)
    - CPU: Multi-agent orchestration, pre/post-processing
    - DRAM: KV cache expansion, memory vaults, vector stores
    
    Route selection logic:
    1. GPU-only models → GPU inference
    2. Hybrid models → GPU compute + DRAM KV cache
    3. CPU-only models → CPU inference with multi-agent routing
    """
    
    def __init__(self):
        self.models = {}
        self.system_resources = self._detect_system()
        
    def _detect_system(self) -> Dict:
        """Detect available system resources."""
        try:
            import psutil
            cpu_count = psutil.cpu_count(logical=True)
            ram_mb = (psutil.virtual_memory().total / 1024**2) - (psutil.virtual_memory().available / 1024**2)
            
            # Check GPU availability
            gpu_available = False
            try:
                import nvidia.mlapi
                if hasattr(nvidia.mlapi, 'MLAPI_GPU_COUNT'):
                    gpu_available = True
            except ImportError:
                gpu_available = False
            
            return {
                "cpu_cores": cpu_count,
                "ram_mb": ram_mb,
                "gpu_available": gpu_available,
                "gpu_memory_gb": 24 if gpu_available else 0
            }
        except Exception as e:
            return {"cpu_cores": 32, "ram_mb": 128, "gpu_available": True, "gpu_memory_gb": 24}
    
    def register_model(self, config: ModelConfig):
        """Register a model configuration."""
        self.models[config.name] = config
    
    def route_request(self, request: Dict) -> str:
        """
        Route an inference request to the optimal resource.
        
        Args:
            request: Dictionary with keys:
                - 'model_family': One of 'QWYTHOS', 'MUSE_GLIMMER', 'GPT_OSS'
                - 'max_context': Maximum context window required
                - 'batch_size': Number of concurrent requests
                
        Returns:
            String describing the routing decision
        """
        
        # Determine which models are available for this family
        model_family = request.get('model_family', '').upper()
        
        if model_family == "QWYTHOS":
            return self._route_qwythos(request)
        elif model_family == "MUSE_GLIMMER":
            return self._route_muse_glimmer(request)
        else:  # GPT_OSS or other
            return self._route_generic(request, model_family)
    
    def _route_qwythos(self, request: Dict) -> str:
        """Route QWYTHOS-9B models (main brain)."""
        
        config = self.models.get("QWYTHOS_9B")
        if not config:
            return "ERROR: No QWYTHOS model configured"
        
        gpu_available = self.system_resources["gpu_available"]
        gpu_memory_needed = request.get("batch_size", 1) * 2  # ~2GB per request
        
        if gpu_available and gpu_memory_needed <= self.system_resources["gpu_memory_gb"]:
            return "GPU: QWYTHOS-9B Claude Mythos 5 (1M context, FP16/Q4_K_M)"
        else:
            return "CPU+DRAM: QWYTHOS-9B fallback mode"
    
    def _route_muse_glimmer(self, request: Dict) -> str:
        """Route Muse Glimmer 30B models."""
        
        config = self.models.get("MUSE_GLIMMER_30B")
        if not config:
            return "ERROR: No Muse Glimmer model configured"
        
        # Muse Glimmer requires GPU for optimal performance
        if self.system_resources["gpu_available"]:
            return "GPU: Muse-Glimmer-30B (30B parameters, hybrid routing)"
        else:
            return "CPU+DRAM: Muse-Glimmer-30B fallback mode"
    
    def _route_generic(self, request: Dict, model_family: str) -> str:
        """Generic router for other model families."""
        
        if self.system_resources["gpu_available"]:
            return f"GPU: {model_family.upper()} (primary inference)"
        else:
            return "CPU+DRAM: Fallback mode"


def main():
    """Demonstrate hybrid routing capabilities."""
    
    router = HybridRouter()
    
    # Register model con
