// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-tasks.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-tasks.ts
var list_tasks_default = defineTool({
  name: "list_tasks",
  title: "List tasks",
  description: "List the signed-in user's Jackie tasks, newest first. Optionally filter by status.",
  inputSchema: {
    status: z.string().optional().describe("Filter by task status, e.g. pending, in_progress, done."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("jackie_tasks").select("id,title,description,status,priority,category,due_date,created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var create_task_default = defineTool2({
  name: "create_task",
  title: "Create task",
  description: "Create a new Jackie task for the signed-in user.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Short task title."),
    description: z2.string().optional().describe("Optional longer detail."),
    priority: z2.string().optional().describe("Priority, e.g. low, medium, high."),
    category: z2.string().optional().describe("Optional grouping category."),
    due_date: z2.string().optional().describe("Optional ISO 8601 due date.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, priority, category, due_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("jackie_tasks").insert({
      user_id: ctx.getUserId(),
      title,
      description: description ?? null,
      priority: priority ?? "medium",
      category: category ?? null,
      due_date: due_date ?? null
    }).select("id,title,status,priority,category,due_date,created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { task: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/update-task-status.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var update_task_status_default = defineTool3({
  name: "update_task_status",
  title: "Update task status",
  description: "Change the status of one of the signed-in user's Jackie tasks.",
  inputSchema: {
    id: z3.string().trim().min(1).describe("Task id (uuid)."),
    status: z3.string().trim().min(1).describe("New status, e.g. pending, in_progress, done.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("jackie_tasks").update({ status }).eq("id", id).select("id,title,status,priority,updated_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return { content: [{ type: "text", text: `No task found with id ${id}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0]) }],
      structuredContent: { task: data[0] }
    };
  }
});

// src/lib/mcp/tools/search-memory.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var search_memory_default = defineTool4({
  name: "search_memory",
  title: "Search Jackie memory",
  description: "Search the signed-in user's Jackie long-term memory entries by key or value text.",
  inputSchema: {
    query: z4.string().trim().optional().describe("Text to match against memory key or value. Omit to list recent entries."),
    category: z4.string().optional().describe("Optional category filter."),
    limit: z4.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("jackie_memory").select("id,key,value,category,confidence,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (category) q = q.eq("category", category);
    if (query) {
      const safe = query.replace(/[%,()]/g, " ").trim();
      if (safe) q = q.or(`key.ilike.%${safe}%,value.ilike.%${safe}%`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/remember-fact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var remember_fact_default = defineTool5({
  name: "remember_fact",
  title: "Remember a fact",
  description: "Store or overwrite a fact in the signed-in user's Jackie long-term memory.",
  inputSchema: {
    key: z5.string().trim().min(1).describe("Stable identifier for the fact."),
    value: z5.string().trim().min(1).describe("The fact to remember."),
    category: z5.string().optional().describe("Optional category, e.g. preference, project, constraint.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ key, value, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: existing, error: findError } = await supabase.from("jackie_memory").select("id").eq("key", key).limit(1);
    if (findError) return { content: [{ type: "text", text: findError.message }], isError: true };
    const { data, error } = existing?.length ? await supabase.from("jackie_memory").update({ value, ...category ? { category } : {} }).eq("id", existing[0].id).select("id,key,value,category,updated_at") : await supabase.from("jackie_memory").insert({ user_id: userId, key, value, category: category ?? "general" }).select("id,key,value,category,updated_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { entry: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/list-conversations.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var list_conversations_default = defineTool6({
  name: "list_conversations",
  title: "List conversations",
  description: "List the signed-in user's Jackie chat conversations, most recently updated first.",
  inputSchema: {
    limit: z6.number().int().min(1).max(100).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("conversations").select("id,title,model,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iezgzdhhmwmbqshnxrie";
var mcp_default = defineMcp({
  name: "sas-jacky",
  title: "SAS-JACKY",
  version: "0.1.0",
  instructions: "Tools for SAS-JACKY (Jackie). Read and manage the signed-in user's tasks, long-term memory facts, and chat conversations. All tools act as the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_tasks_default, create_task_default, update_task_status_default, search_memory_default, remember_fact_default, list_conversations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
